# 应用服务 WEB 访问端口
server:
  port: 9090
  servlet:
    context-path: /api
spring:
  application:
    name: DataAnalyze
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_analyze?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: abc8909389
  elasticsearch:
    rest:
      uris: http://172.27.159.36:9200
      read-timeout: 30s
      connection-timeout: 30s
rocketmq:
  # rocketmq 对应地址
    name-server: 47.120.8.78:9876
    producer:
      group: producer_group # 必须指定group
      send-message-timeout: 3000 # 消息发送超时时长，默认3s
      retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
      retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
zhiji:
  apiKey: 3ae622ed2c8edafb59318893d454adaf.N0Z0Id6Qxd52ePyc



